freeSpace: "Will plays green"
options:
  - "Someone claims a rule was never explained"
  - "Wear an old Danycon shirt"
  - "Play a paranormal game"
  # - "Critical hit!"
  # - "Critical miss!"
  - "Dany forces someone to keep petting her"
  - "Conversation about feminism occurs"
  - "Someone other than Will explains the rules"
  - "Win a game"
  - "Come in last in a multiplayer game"
  - "Play a game not on the website"
  - "Someone rolls a non-numeric die"
  - "Wildlife spotted outside"
  - "Dany barks to go out"
  - "A game goes to tie breaker"
  - '"Whose turn is it?"'
  - '"Can I take my turn back?"'
  - "Bailey watches sports on her phone"
  - "3 or more people wear the same old Danycon shirt"
  - "Finish all the word games one day"
  - "Someone quotes Spongebob"
  - "Someone quotes Emperor's New Groove"
  - "There are lots of leftovers"
  - "Will plays a color that is not green"
  - "Lexi apologizes"
  - 'Jesse exclaims "Gottem!" or similar'
  - "Mary Elizabeth brags about being a great sister"
  - "Mark and Erin talk about Finn and Ari"
  - "Will and Lexi talk about Julius and Patricia"
  - "Mandy orders a board game"
  - "Someone asks if we are going to Rota"
  - "We skip an item on the Danycon schedule"
  - "Unused tokens are punched"
  - "Play a game you have played before"
  - "Someone goes to the grocery store"
